# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Hector's Blog 
# Description of the Site
description: Hector Quemada's blog site 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.unsplash.com/photo-1546547375-cefab0de4484?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hdquemada@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: hdquemada
github_username:  hdquemada
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-YC59PDXQ6H 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Hector Quemada
# URL for the Image of the Author
author-image: assets/images/headshot.png 
# 60 Words About the Author
author-about: Hello! This is my personal blog, which is still under construction but scheduled to be fully functional by June 30, 2022.  That is the day of my retirement, which will give me more time to devote to blogging, among other things. In the meantime, please see <a href="https://hdquemada.github.io" target="_blank">my professional website</a>.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/hdquemada

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
